import { Column } from "./../interfaces";
export const columns: Column[] = [
  { display: "Instance", id: "trackedEntityInstance", selected: true },
  { display: "Beneficiary ID", id: "RDEklSXCD4C.HLKc2AKR9jW", selected: true },
  {
    display: "Old Beneficiary ID",
    id: "RDEklSXCD4C.e0zEpTw7IH6",
    selected: true,
  },
  { display: "Household Code", id: "RDEklSXCD4C.tHCT4RKXoiU", selected: true },
  {
    display: "Enrollment Date",
    id: "RDEklSXCD4C.enrollmentDate",
    selected: true,
  },

  {
    display: "Type(Comprehensive, Prevention)",
    id: "RDEklSXCD4C.type",
    selected: true,
  },
  { display: "District", id: "district", selected: true },
  { display: "Sub-county", id: "subCounty", selected: true },
  { display: "Parish", id: "RDEklSXCD4C.orgUnitName", selected: true },
  { display: "Village", id: "HEWq6yr4cs5.Xkwy5P2JG24", selected: true },
  { display: "Household Head", id: "HEWq6yr4cs5.ExnzeYjgIaT", selected: true },
  {
    display: "Primary Caregiver",
    id: "primaryCareGiver",
    selected: true,
  },
  {
    display: "Date of Assessment",
    id: "HEWq6yr4cs5.sYE3K7fFM4Y.eventDate",
    selected: true,
  },
  {
    display: "Beneficiary Name",
    id: "RDEklSXCD4C.huFucxA3e5c",
    selected: true,
  },
  { display: "DOB", id: "RDEklSXCD4C.N1nMqKtYKvI", selected: true },
  { display: "Age", id: "RDEklSXCD4C.age", selected: true },
  { display: "Age Group", id: "RDEklSXCD4C.ageGroup", selected: true },
  { display: "Sex", id: "RDEklSXCD4C.CfpoFtRmK1z", selected: true },
  {
    display: "Risk Factor",
    id: "riskFactor",
    selected: true,
  },
  {
    display: "Household status",
    id: "householdStatus",
    selected: true,
  },
  { display: "Member status", id: "memberStatus", selected: true },
  {
    display: "Currently Enrolled in School (Y/N)",
    id: "enrolledInSchool",
    selected: true,
  },
  { display: "Newly enrolled", id: "newlyEnrolled", selected: true },
  { display: "HIV_Status(+,-,?, -/+)", id: "hivStatus", selected: true },
  {
    display: "OVC_TST ASSESS",
    id: "RDEklSXCD4C.B9EI27lmQrZ.vBqh2aiuHOV",
    selected: true,
  },
  {
    display: "OVC_TST RISK",
    id: "isAtRisk",
    selected: true,
  },
  {
    display: "OVC_TST REFER",
    id: "RDEklSXCD4C.yz3zh5IFEZm.reason",
    selected: true,
  },
  {
    display: "OVC_TST REPORT",
    id: "RDEklSXCD4C.yz3zh5IFEZm.hivResult",
    selected: true,
  },
  {
    display: "HIV test not required based on  HIV risk Assessment",
    id: "isNotAtRisk",
    selected: true,
  },
  {
    display: "Unknown HIV status: other reasons",
    id: "unknown",
    selected: true,
  },
  {
    display: "Linked to HTS (referred for Testing) (1 Yes, 0 No)",
    id: "RDEklSXCD4C.B9EI27lmQrZ.linked",
    selected: true,
  },
  {
    display: "Tested for HIV (1 Yes, 0 No)",
    id: "RDEklSXCD4C.B9EI27lmQrZ.testedForHIV",
    selected: true,
  },
  {
    display: "Newly Reported HIV Positive (1 Yes, 0 No)",
    id: "newlyPositive",
    selected: true,
  },

  {
    display: "Newly Tested HIV Positive (1 Yes, 0 No)",
    id: "newlyTestedPositive",
    selected: true,
  },
  {
    display: "Newly Tested HIV Positive initiated on ART (1 Yes, 0 No)",
    id: "newlyTestedAndOnArt",
    selected: true,
  },
  { display: "ART No", id: "artNo", selected: true },
  {
    display: "On_ART_HVAT (1 Yes, 0 No)",
    id: "RDEklSXCD4C.umqeJCVp4Zq",
    selected: true,
  },
  {
    display: "On_ART_VL (1 Yes, 0 No)",
    id: "onArt",
    selected: true,
  },
  {
    display: "Facility",
    id: "facility",
    selected: true,
  },
  {
    display: "OVC_VL Eligible (1 Yes, 0 No)",
    id: "ovcEligible",
    selected: true,
  },
  {
    display: "Last Viral Load Date",
    id: "lastViralLoadDate",
    selected: true,
  },
  { display: "VLTest done (1 Yes, 0 No)", id: "VLTestDone", selected: true },
  { display: "OVC_VLR (1 Yes, 0 No, Waiting )", id: "ovcVL", selected: true },
  {
    display: "Viral Load Status (Suppressed, Non Suppressed, Waiting)",
    id: "VLStatus",
    selected: true,
  },
  {
    display: "Viral Load Copies",
    id: "copies",
    selected: true,
  },
  { display: "OVC_VLS (1 Yes, 0 No))", id: "VLSuppressed", selected: true },
  { display: "VSLA", id: "VSLA", selected: true },
  { display: "Financial Literacy", id: "fLiteracy", selected: true },
  { display: "Bank Linkages", id: "bankLinkages", selected: true },
  { display: "Agribusiness", id: "agriBusiness", selected: true },
  { display: "SPM Training", id: "spmTraining", selected: true },
  { display: "Micro-Franchise", id: "micro", selected: true },
  { display: "IGA Booster", id: "igaBooster", selected: true },
  {
    display: "Temporary Consumption support",
    id: "tempConsumption",
    selected: true,
  },
  { display: "VSLA+ OVCFund", id: "vlsaOvcFund", selected: true },
  { display: "Core_ES", id: "coreES", selected: true },
  { display: "Education subsidy", id: "educationSubsidy", selected: true },
  { display: "Home Learning", id: "homeLearning", selected: true },
  { display: "NFE", id: "nonFormalEducation", selected: true },
  { display: "core_education", id: "coreEducation", selected: true },
  { display: "HTS referral", id: "HTSReferral", selected: true },
  {
    display: "Non Disclosure Support",
    id: "nonDisclosureSupport",
    selected: true,
  },
  {
    display: "Antiretroviral Therapy (ART) Initiation",
    id: "artInitiation",
    selected: true,
  },
  {
    display: "ART_Adherence_Education",
    id: "artAdherenceEducation",
    selected: true,
  },
  {
    display: "Intensive Adherence Counseling (IAC)",
    id: "iac",
    selected: true,
  },
  { display: "EMTCT", id: "eMTCT", selected: true },
  { display: "HIV prevention Education", id: "hivPrevention", selected: true },
  { display: "Journeys MOH", id: "journeysMOH", selected: true },
  { display: "Journeys LARA", id: "journeysLARA", selected: true },
  { display: "NMN (Boys)", id: "NMNBoys", selected: true },
  { display: "NMN (Girls)", id: "NMNGirls", selected: true },
  { display: "TF_Health", id: "TFHealth", selected: true },
  { display: "PEP Service", id: "PEP", selected: true },
  { display: "COVID 19 Education", id: "covid19Education", selected: true },
  {
    display: "Other Health Related Services",
    id: "otherHealthServices",
    selected: true,
  },
  { display: "core_health", id: "coreHealth", selected: true },
  {
    display: "GBV Prevention Education",
    id: "GBVPreventionEducation",
    selected: true,
  },
  { display: "TF_GBV", id: "TFGBV", selected: true },
  { display: "Legal support", id: "referral4LegalSupport", selected: true },
  { display: "ECD", id: "ECD", selected: true },
  { display: "Parenting", id: "parenting", selected: true },
  {
    display: "Child Protection Education",
    id: "childProtectionEducation",
    selected: true,
  },
  {
    display: "Core_child_protection",
    id: "coreChildProtection",
    selected: true,
  },
  { display: "Nutrition education", id: "nutritionEducation", selected: true },
  {
    display: "voucher for crops",
    id: "voucher4CropsOrKitchenGardens",
    selected: true,
  },
  {
    display: "TF_NutritionalSupport",
    id: "nutritionalAssessment",
    selected: true,
  },
  { display: "core_nutrition", id: "coreNutrition", selected: true },
  { display: "PSS", id: "psychosocialSupport", selected: true },
  { display: "core_pss", id: "corePSS", selected: true },
  {
    display: "Served in Current Reporting Quarter",
    id: "quarter",
    selected: true,
  },
  {
    display: "Served_in_Previous Quarter say Q3((1 Yes, 0 No, )",
    id: "servedInPreviousQuarter",
    selected: true,
  },
  { display: "Graduated(1 Yes, 0 No, )", id: "graduated", selected: true },
  { display: "OVC_SERV(1 Yes, 0 No, )", id: "OVC_SERV", selected: true },
  { display: "OVC_ENROL", id: "OVC_ENROL", selected: true },
  { display: "OVC_SERV_SUBPOP", id: "OVC_SERV_SUBPOP", selected: true },
  {
    display: "OVC_HIV STAT (1 Yes, 0 No, )",
    id: "OVC_HIV_STAT",
    selected: true,
  },
  {
    display: "Exited With Graduation",
    id: "exitedWithGraduation",
    selected: true,
  },
  {
    display: "Transferred to Other PEPFAR IP",
    id: "otherPERFARIP",
    selected: true,
  },
  { display: "Transferred to Other IP", id: "otherIP", selected: true },
];
